---
language: java
sudo: false
script: mvn clean verify

deploy:
   provider: cloudfoundry
   username: richar.fernandezv@gmail.com
   password:
    secure: "jg1wuxAricOHHZML+itPJX4VxjQkY+R7TXwU/lZ29zMimJP5Q0wAepKxp70LOrrXbQfg4Lu6Es2vOBUgNtwGcGzlHJu+hG/TMfn7duSSCF5cBaSy46Mkz85Nt1EAIo8D5pGtXHGE9frGMSXK+2EWsXCPN0PvlJEEN8XI4/B4EfA8JpYvWQA1Ociw59FWRZRdbxK4THURBRVmANa7/COSXLKv4VsMJ3488un9OEf0n1BnE0RdIpu+AhzBKoa7M1gmNI0acFSbODvVHDEW+4sp0z4mWEjlQFH1xPOqoVHPpyESwyqlHMkngDGo92TDXWdhy7O6629qTDoB/4qZkDMCgUS+//zowXF1M1INpf6U5l+qNZN+ElCPPDAxcOkcLxxNRpPrz612e9AYGCEPa9jh9NZoRT92hZ3LzKfVxQPMc9fJ7/FGELgglznnyRsvwlJgAnpxoVlKu0TvxgCSX3RbHgf5vTmhuOsO0VcFFOTFhPZCwQJuNbVMCP5FyRmWRVpCfBL0YSd0btbIwO8Co0YzDsbRSk/l0qjiccZb4diI3RSbbMkifYQn5A0P++DiRupvSEhp3O2fXYe+VVpxByr112dA8ai7gW2LTwFPn1dM04rXl+vKSOI5cyOMMGeMGsjfES7s2akUjJozerFljO+6hb2CsTfNu93TYhSX6iagrWc="
   api: https://api.run.pivotal.io
   organization: rfernandezv
   space: development